version: '2.4'
services:
  node:
    tty: true
    stdin_open: true
    container_name: redis-connect
    build:
      context: .
      args:
        - NPM_TOKEN
    depends_on:
      - redis
    volumes:
      - '.:/home/node/app:rw'
    user: 'node:node'

  redis:
    image: redis:2.8
